export const BILL_CATEGORIES_PAGE = "BILL_CATEGORIES_PAGE";
export const CATEGORY_BILLERS_PAGE = "CATEGORY_BILLERS_PAGE";
export const CUSTOMER_INPUT_PAGE = "CUSTOMER_INPUT_PAGE";
export const PRODUCTS_PAGE = "PRODUCTS_PAGE";
