export const UPDATE_BILL_CATEGORY = "UPDATE_BILL_CATEGORY";
export const UPDATE_CATEGORY_BILLER = "UPDATE_CATEGORY_BILLER";
export const UPDATE_CUSTOMER_ID = "UPDATE_CUSTOMER_ID";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
